services:
  postgres:
    container_name: postgres
    image: postgres:15.3-alpine3.17
    env_file:
      - .env.production
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - '3000:3000'
    volumes:
      - ./public:/usr/src/app/public
    depends_on:
      - postgres

volumes:
  pgdata:
